apiVersion: v1
kind: Service
metadata:
  name: mcp-weather-service
  namespace: weather
  labels:
    app: mcp-weather-app
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: mcp-weather-app
